# Generated by Django 5.2.3 on 2025-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaynowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(help_text='Your Paynow Integration ID (e.g., from Paynow dashboard).', max_length=255)),
                ('integration_key', models.CharField(help_text='Your Paynow Integration Key (e.g., from Paynow dashboard).', max_length=255)),
                ('api_base_url', models.URLField(default='https://www.paynow.co.zw/interface/remotetransaction', help_text='Base URL for Paynow API transactions.')),
            ],
            options={
                'verbose_name': 'Paynow Configuration',
                'verbose_name_plural': 'Paynow Configurations',
            },
        ),
    ]
