# Generated by Django 5.1.7 on 2025-05-23 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_contact_intervention_requested_at_and_more'),
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactflowstate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contactflowstate',
            name='contact',
            field=models.OneToOneField(help_text='The contact engaged in the flow. A contact can only be in one flow state at a time.', on_delete=django.db.models.deletion.CASCADE, related_name='flow_state', to='conversations.contact'),
        ),
        migrations.AlterField(
            model_name='contactflowstate',
            name='flow_context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data collected from the user or set during this flow instance (e.g., answers to questions).'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='trigger_keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords/phrases that can trigger this flow (e.g., ["hello", "start session"]). Case-insensitive \'contains\' match.'),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='step_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('question', 'Ask Question'), ('condition', 'Conditional Branch'), ('action', 'Perform Action'), ('wait_for_reply', 'Wait for Reply'), ('end_flow', 'End Flow'), ('start_flow_node', 'Start Flow Node'), ('human_handover', 'Handover to Human Agent')], max_length=50),
        ),
    ]
