# Generated by Django 5.1.7 on 2025-05-18 00:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(db_index=True, help_text="The user's WhatsApp ID (phone number).", max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of the contact, as provided by WhatsApp or manually entered.', max_length=255, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the contact was first created.')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp of the last interaction (message) with this contact.')),
                ('is_blocked', models.BooleanField(default=False, help_text='If the CRM has blocked this contact.')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(blank=True, db_index=True, help_text='WhatsApp Message ID (from Meta), unique for sent/received messages.', max_length=255, null=True)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], help_text='Direction of the message.', max_length=3)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive Message'), ('button', 'Button Reply'), ('system', 'System Message'), ('unknown', 'Unknown'), ('unsupported', 'Unsupported'), ('crm_note', 'CRM Internal Note'), ('flow_trigger', 'Flow Trigger (Internal)')], default='text', help_text='Type of WhatsApp message.', max_length=20)),
                ('content_payload', models.JSONField(help_text='Raw message payload from/to Meta API.')),
                ('text_content', models.TextField(blank=True, help_text="Text content if it's a text message.", null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the message (from Meta or when CRM processed it).')),
                ('status', models.CharField(choices=[('pending', 'Pending Send'), ('sent', 'Sent to Meta'), ('delivered', 'Delivered to User'), ('read', 'Read by User'), ('failed', 'Failed to Send'), ('deleted', 'Deleted'), ('received', 'Received')], default='pending', help_text='Status of the message.', max_length=20)),
                ('status_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of the last status update.', null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Error details if message sending failed.', null=True)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.contact')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['contact', 'timestamp'], name='conversatio_contact_fa930b_idx'), models.Index(fields=['wamid'], name='conversatio_wamid_13e839_idx'), models.Index(fields=['message_type'], name='conversatio_message_792495_idx'), models.Index(fields=['status', 'direction'], name='conversatio_status_d3617d_idx')],
            },
        ),
    ]
