# Generated by Django 5.1.7 on 2025-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='intervention_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when human intervention was last requested.', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='needs_human_intervention',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to true if this contact requires human attention.'),
        ),
    ]
