# Generated by Django 5.1.7 on 2025-05-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_contact_intervention_requested_at_and_more'),
        ('flows', '0002_alter_contactflowstate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='triggered_by_flow_step',
            field=models.ForeignKey(blank=True, help_text='The flow step that triggered the creation of this message, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_messages', to='flows.flowstep'),
        ),
    ]
