# Generated by Django 5.1.7 on 2025-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_message_triggered_by_flow_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='out', help_text='Direction of the message.', max_length=3),
        ),
    ]
