# Generated by Django 5.1.7 on 2025-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_contact_current_flow_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='flow_execution_disabled',
            field=models.BooleanField(default=False, help_text='If true, automated flow processing is paused for this contact (e.g., during human agent interaction).'),
        ),
    ]
