# Generated by Django 5.1.7 on 2026-01-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_contact_flow_execution_disabled'),
        ('meta_integration', '0004_webhookeventlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='associated_app_config',
            field=models.ForeignKey(
                blank=True,
                help_text='The Meta App Configuration this contact is associated with (the phone number they message).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contacts',
                to='meta_integration.metaappconfig'
            ),
        ),
    ]
