# Generated by Django 5.2.17 on 2026-09-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_contact_associated_app_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the contact is currently authenticated.",
                    ),
                ),
                (
                    "authenticated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the contact last authenticated.",
                        null=True,
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last activity in this session.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the session expires.",
                        null=True,
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        help_text="The contact this session belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="conversations.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Session",
                "verbose_name_plural": "Contact Sessions",
            },
        ),
    ]
