# Generated by Django 5.2.17 on 2026-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_integration", "0004_webhookeventlog_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaappconfig",
            name="flow_private_key_pem",
            field=models.TextField(
                blank=True,
                help_text="PEM-encoded RSA private key for WhatsApp Flows encryption/decryption. Generated by the setup_flow_encryption management command.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaappconfig",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to enable this configuration. Multiple configurations can be active simultaneously.",
            ),
        ),
        migrations.AlterField(
            model_name="metaappconfig",
            name="phone_number_id",
            field=models.CharField(
                help_text="The Phone Number ID from which messages will be sent. Must be unique across all configurations.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
