# Generated by Django 5.1.7 on 2025-06-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_code', models.CharField(db_index=True, max_length=10)),
                ('competition_name', models.CharField(blank=True, max_length=100, null=True)),
                ('match_api_id', models.IntegerField(help_text='Match ID from football-data.org', unique=True)),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_team_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('away_team_name', models.CharField(max_length=100)),
                ('away_team_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('match_datetime_utc', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('last_api_update', models.DateTimeField(blank=True, help_text='Timestamp of the last update from the API for this match', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Football Fixture',
                'verbose_name_plural': 'Football Fixtures',
                'ordering': ['match_datetime_utc'],
            },
        ),
    ]
