# Generated by Django 5.1.7 on 2025-06-05 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data_app', '0002_bookmaker_league_marketcategory_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betselection',
            name='bet',
        ),
        migrations.AlterUniqueTogether(
            name='betselection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='betselection',
            name='market_outcome',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='footballfixture',
            options={'ordering': ['commence_time']},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['fixture_display', 'bookmaker', 'category']},
        ),
        migrations.AlterModelOptions(
            name='marketcategory',
            options={'verbose_name_plural': 'Market Categories'},
        ),
        migrations.RemoveField(
            model_name='bookmaker',
            name='api_bookmaker_id',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='api_fixture_timestamp',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='extratime_away_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='extratime_home_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='halftime_away_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='halftime_home_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='is_result_confirmed',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='last_updated_from_api',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='match_api_id',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='penalty_away_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='penalty_home_score',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='round',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='status_long',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='status_short',
        ),
        migrations.RemoveField(
            model_name='footballfixture',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='league',
            name='api_league_id',
        ),
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
        migrations.RemoveField(
            model_name='league',
            name='logo_url',
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('fixture_display', 'bookmaker', 'api_market_key')},
        ),
        migrations.AlterUniqueTogether(
            name='marketoutcome',
            unique_together={('market', 'outcome_name', 'point_value')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='api_team_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='api_bookmaker_key',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='last_update_from_api',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='away_team_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='commence_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='event_api_id',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='home_team_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='last_odds_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='last_score_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='sport_key',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='league',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='last_fetched_events',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='sport_key',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='sport_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='market',
            name='api_market_key',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='fixture_display',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='football_data_app.footballfixture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marketoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketoutcome',
            name='point_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='marketoutcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footballfixture',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football_data_app.league'),
        ),
        migrations.AlterField(
            model_name='market',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='football_data_app.marketcategory'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_parameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketoutcome',
            name='odds',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketoutcome',
            name='result_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void'), ('HALF_WON', 'Half Won'), ('HALF_LOST', 'Half Lost'), ('PUSH', 'Push')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='BetSelection',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.RemoveField(
            model_name='market',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='market',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketoutcome',
            name='is_suspended',
        ),
    ]
