# Generated by Django 5.1.7 on 2025-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data_app', '0003_remove_betselection_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfixture',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
