# Generated by Django 5.2.17 on 2026-09-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_data_app", "0003_alter_league_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixturePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prob_home",
                    models.FloatField(
                        help_text="Probability the home team wins (0-1)."
                    ),
                ),
                (
                    "prob_draw",
                    models.FloatField(help_text="Probability of a draw (0-1)."),
                ),
                (
                    "prob_away",
                    models.FloatField(
                        help_text="Probability the away team wins (0-1)."
                    ),
                ),
                ("expected_home_goals", models.FloatField(blank=True, null=True)),
                ("expected_away_goals", models.FloatField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        default="poisson",
                        help_text="Model used, e.g. 'poisson'.",
                        max_length=30,
                    ),
                ),
                (
                    "data_points",
                    models.IntegerField(
                        default=0,
                        help_text="Number of historical matches the estimate is based on (confidence).",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fixture Prediction",
                "verbose_name_plural": "Fixture Predictions",
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="current_season",
            field=models.IntegerField(
                default=2024,
                help_text="Current season year for API-Football v3 (e.g., 2024). Used when fetching fixtures and standings.",
            ),
        ),
        migrations.AddField(
            model_name="footballfixture",
            name="elapsed_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Minutes elapsed in a LIVE match (e.g. 62), from the provider's fixture status. Meaningless once the match isn't LIVE.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="footballfixture",
            name="match_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the match was last updated by the API (from match_updated field). Per APIFootball.com documentation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="provider_name",
            field=models.CharField(
                choices=[
                    ("API-Football", "API-Football (api-football.com) - Recommended"),
                    ("APIFootball", "APIFootball (apifootball.com)"),
                    ("The Odds API", "The Odds API"),
                ],
                default="APIFootball",
                help_text="Football data API provider. API-Football (api-football.com) is recommended for new installations.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="bookmaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmaker_markets",
                to="football_data_app.bookmaker",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_markets",
                to="football_data_app.marketcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="footballfixture",
            index=models.Index(
                fields=["status", "match_date"], name="fixture_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="footballfixture",
            index=models.Index(
                fields=["last_odds_update"], name="fixture_last_odds_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["fixture", "is_active"], name="market_fixture_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketoutcome",
            index=models.Index(
                fields=["market", "is_active"], name="outcome_market_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="fixtureprediction",
            name="fixture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prediction",
                to="football_data_app.footballfixture",
            ),
        ),
    ]
