# Generated by Django 5.2.17 on 2026-09-06 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_data",
            "0006_playerloginotp_responsiblegamblingcontrols_bet_odds_and_more",
        ),
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralsettings",
            options={
                "verbose_name": "Agent Program Settings",
                "verbose_name_plural": "Agent Program Settings",
            },
        ),
        migrations.AddField(
            model_name="referralsettings",
            name="agent_win_deduction_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.2500"),
                help_text="The percentage of a won bet's winnings (e.g., 0.25 for 25%) deducted from the agent's wallet when a user they referred wins.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="referralsettings",
            name="agent_commission_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.2500"),
                help_text="The percentage of a lost bet's stake (e.g., 0.25 for 25%) awarded to the agent who referred the losing bettor.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="referralsettings",
            name="bonus_percentage_each",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.2500"),
                help_text="The bonus percentage (e.g., 0.25 for 25%) given to both the referrer (if a designated agent) and the referred user on the referred user's qualifying first deposit.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="AgentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("win_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deduction_percentage",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "deduction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_deductions",
                        to="referrals.referralprofile",
                    ),
                ),
                (
                    "bet_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_deductions",
                        to="customer_data.betticket",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentDepositBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "bonus_percentage",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("bonus_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_bonuses",
                        to="referrals.referralprofile",
                    ),
                ),
                (
                    "deposit_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_deposit_bonuses",
                        to="customer_data.wallettransaction",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_signup_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Deposit Bonus",
                "verbose_name_plural": "Agent Deposit Bonuses",
                "ordering": ["-created_at"],
            },
        ),
    ]
