# Generated by Django 5.1.7 on 2025-05-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='acquisition_source',
            field=models.CharField(blank=True, help_text="How this customer was acquired, e.g., 'Ad Campaign X', 'Website Signup', 'Referral'", max_length=150, null=True, verbose_name='Acquisition Source'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lifecycle_stage',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('vip', 'VIP Customer'), ('churned', 'Churned'), ('other', 'Other')], default='lead', max_length=50, null=True, verbose_name='Lifecycle Stage'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the customer.', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='An alternative phone number, if provided.', max_length=30, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Descriptive tags for segmentation, e.g., ['product_x_interest', 'webinar_attendee']", verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
