# Generated by Django 5.1.7 on 2025-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0002_customerprofile_acquisition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='ecocash_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
