# Generated by Django 5.2.3 on 2025-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0002_customerprofile_acquisition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Reference from the external payment gateway (e.g., Paynow).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Our internal unique reference for the transaction.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='COMPLETED', max_length=20),
        ),
    ]
