# Generated by Django 5.2.3 on 2025-06-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0003_wallettransaction_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores details for the payment method, e.g., phone number for mobile money.'),
        ),
    ]
