# Generated by Django 5.2.3 on 2025-06-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0004_wallettransaction_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWithdrawal',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Withdrawal',
                'verbose_name_plural': 'Pending Withdrawals',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer_data.wallettransaction',),
        ),
    ]
