# Generated by Django 5.2.17 on 2026-09-06 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0008_contactsession"),
        ("customer_data", "0005_pendingwithdrawal"),
        ("football_data_app", "0004_fixtureprediction_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerLoginOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponsibleGamblingControls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "self_excluded_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set and in the future, the user cannot bet or deposit until this time.",
                        null=True,
                    ),
                ),
                (
                    "daily_deposit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum total deposits per 24h. Blank means no limit.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "daily_stake_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum total stakes per 24h. Blank means no limit.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has passed identity/age (KYC) verification.",
                    ),
                ),
                ("kyc_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Responsible Gambling Controls",
                "verbose_name_plural": "Responsible Gambling Controls",
            },
        ),
        migrations.AddField(
            model_name="bet",
            name="odds",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Odds agreed at placement. Settlement pays at this price, not the current market price.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="market_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bets",
                to="football_data_app.marketoutcome",
            ),
        ),
        migrations.AlterField(
            model_name="betticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PLACED", "Placed"),
                    ("WON", "Won"),
                    ("LOST", "Lost"),
                    ("PARTIAL_WIN", "Partial Win"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("BET_PLACED", "Bet Placed"),
                    ("BET_WON", "Bet Won"),
                    ("BET_LOST", "Bet Lost"),
                    ("BET_REFUNDED", "Bet Refunded"),
                    ("AGENT_COMMISSION", "Agent Commission"),
                    ("AGENT_DEPOSIT_BONUS", "Agent Deposit Bonus"),
                    ("AGENT_WIN_DEDUCTION", "Agent Win Deduction"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="betticket",
            index=models.Index(
                fields=["user", "-created_at"], name="ticket_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="betticket",
            index=models.Index(fields=["status"], name="ticket_status_idx"),
        ),
        migrations.AddField(
            model_name="playerloginotp",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_otps",
                to="conversations.contact",
            ),
        ),
        migrations.AddField(
            model_name="responsiblegamblingcontrols",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rg_controls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="playerloginotp",
            index=models.Index(
                fields=["contact", "consumed", "expires_at"],
                name="customer_da_contact_8bf85d_idx",
            ),
        ),
    ]
