# Generated by Django 5.2.11 on 2026-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0005_pendingwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('WON', 'Won'), ('LOST', 'Lost'), ('PARTIAL_WIN', 'Partial Win'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BET_PLACED', 'Bet Placed'), ('BET_WON', 'Bet Won'), ('BET_LOST', 'Bet Lost'), ('BET_REFUNDED', 'Bet Refunded'), ('AGENT_COMMISSION', 'Agent Commission')], max_length=20),
        ),
    ]
