# Generated by Django 5.1.7 on 2025-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this media asset (e.g., 'Welcome Offer Image').", max_length=255)),
                ('file', models.FileField(help_text='The actual media file.', upload_to='whatsapp_media_assets/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker')], help_text='The general type of media.', max_length=20)),
                ('mime_type', models.CharField(blank=True, help_text='Specific MIME type. Auto-detected if blank.', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes.', null=True)),
                ('whatsapp_media_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp Media ID. Updated upon successful sync.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('local', 'Local Only - Pending Upload'), ('uploading', 'Uploading to WhatsApp...'), ('synced', 'Synced with WhatsApp'), ('error_upload', 'Initial Upload Error'), ('expired', 'WhatsApp ID Potentially Expired'), ('error_resync', 'Re-sync Error')], db_index=True, default='local', help_text='Sync status with WhatsApp.', max_length=20)),
                ('uploaded_to_whatsapp_at', models.DateTimeField(blank=True, editable=False, help_text='Last successful sync with WhatsApp.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
